inherit_from: ../.rubocop.yml

Layout/ClosingParenthesisIndentation:
  Enabled: false

Layout/EmptyLines:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/MultilineBlockLayout:
  Enabled: false

Layout/SpaceInsideBlockBraces:
  Enabled: false

Layout/SpaceInsideParens:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/BlockDelimiters:
  IgnoredMethods: [ expect, let ]

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NestedParenthesizedCalls:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/WordArray:
  Enabled: false
